main_url = 'https://qa-scooter.praktikum-services.ru'
create_courier_url = '/api/v1/courier'
login_courier_url = '/api/v1/courier/login'
order_url = '/api/v1/orders'
cancel_order_url = f'/api/v1/orders/cancel'